CREATE DATABASE webapp;
USE webapp; 

CREATE TABLE IF NOT EXISTS users (
	id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, 
	fn VARCHAR(60) NOT NULL, 
	ln VARCHAR(60) NOT NULL, 
	email VARCHAR(255) NOT NULL
); 